# Generated by Django 5.0.3 on 2024-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_availability', models.CharField(choices=[('availabe', 'Availabe'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance')], max_length=50)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=50)),
                ('room_number', models.IntegerField()),
                ('capacity', models.CharField(max_length=50)),
                ('amenities', models.TextField()),
            ],
        ),
    ]
