# Generated by Django 5.0.3 on 2024-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(default='images/signUp-bg3.jpg', upload_to='images/'),
        ),
    ]
