# Generated by Django 5.0.3 on 2024-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe ', 'Deluxe '), ('suite', 'Suite'), ('villa', 'Villa'), ('accessible', 'Accessible')], max_length=50),
        ),
    ]
