# Generated by Django 5.0.3 on 2024-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(default=150, max_length=50),
            preserve_default=False,
        ),
    ]
