# Generated by Django 5.0.2 on 2024-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_instagram_link_profile_linked_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default_avatar.jpg', upload_to='images/'),
        ),
    ]
