# Generated by Django 5.0.2 on 2024-04-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linked_link',
        ),
    ]
