# Generated by Django 5.0.3 on 2024-04-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='ingredients',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='category',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Carbs', 'Carbs'), ('Vegetarian', 'Vegetarian'), ('Protien', 'Protien')], max_length=64),
        ),
    ]
