# Generated by Django 4.2.11 on 2024-04-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_contact"),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="place",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="main.place"
            ),
            preserve_default=False,
        ),
    ]
