# Generated by Django 5.0.2 on 2024-04-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
