# Generated by Django 5.0.2 on 2024-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Airbods', 'Airbods'), ('Clothing and Fashion', 'Clothing And Fashion'), ('Health and Beauty', 'Health And Beauty'), ('Sports', 'Sports')], max_length=64),
        ),
    ]
