# Generated by Django 5.0.2 on 2024-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Iphone', 'Iphone'), ('Airbods', 'Airbods'), ('Mackbook', 'Mackbook'), ('Ipad', 'Ipad'), ('Aplle watch', 'Aplle Watch')], max_length=64),
        ),
    ]
