# Generated by Django 5.0.3 on 2024-03-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='number_people',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time_coocking',
            field=models.CharField(max_length=2048),
        ),
    ]
