# Generated by Django 5.0.3 on 2024-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_chfe_name_recipes_chef_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='images/kagyana-2955466_1280.jpg', upload_to='images/'),
        ),
    ]
