# Generated by Django 5.0.3 on 2024-04-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='Recipes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
            preserve_default=False,
        ),
    ]
