# Generated by Django 5.0.3 on 2024-04-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video',
        ),
    ]
