# Generated by Django 5.0.3 on 2024-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/logo.png', upload_to='images/'),
        ),
    ]
