# Generated by Django 5.0.3 on 2024-04-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='brief',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
