# Generated by Django 5.0.3 on 2024-04-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recipe_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='served',
            field=models.IntegerField(default=0),
        ),
    ]
