# Generated by Django 5.0.3 on 2024-04-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_contact_user_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Mix', 'Mix'), ('Carbs', 'Carbs'), ('Vegetarian', 'Vegetarian'), ('Protien', 'Protien')], max_length=64),
        ),
    ]
