# Generated by Django 5.0.3 on 2024-04-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe_ingredients_alter_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='potassium',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.IntegerField(default=44),
            preserve_default=False,
        ),
    ]
