# Generated by Django 5.0.3 on 2024-04-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('interactive', '0002_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='users_recipe',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.userrecipe'),
        ),
    ]
