# Generated by Django 5.0.3 on 2024-04-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_commentfavorite_recipefavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commentFavorite',
        ),
    ]
