# Generated by Django 5.0.2 on 2024-04-03 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_orgnization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootcamp_name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('objectives', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(to='accounts.student')),
            ],
        ),
    ]
