# Generated by Django 5.0.3 on 2024-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
