# Generated by Django 5.0.3 on 2024-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Wildlife & Nature', 'Wildlife & Nature'), ('Arts & Culture', 'Arts & Culture'), ('People & Daily Life', 'People & Daily Life'), ('Food & Drinks', 'Food & Drinks')], max_length=64),
        ),
    ]
