# Generated by Django 5.0.3 on 2024-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
