# Generated by Django 5.0.2 on 2024-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/default_img.png', upload_to='images/'),
        ),
    ]
