# Generated by Django 5.0.2 on 2024-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Arts', 'Arts'), ('Daily', 'Daily'), ('Food', 'Food')], max_length=64),
        ),
    ]
