# Generated by Django 5.0.2 on 2024-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Arts', 'Arts'), ('Daily', 'Daily'), ('Food', 'Food'), ('other', 'Other')], max_length=64),
        ),
    ]
