# Generated by Django 5.0.2 on 2024-04-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
    ]
