# Generated by Django 4.2.11 on 2024-04-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="groups",),
        migrations.RemoveField(model_name="user", name="user_permissions",),
        migrations.DeleteModel(name="Profile",),
        migrations.DeleteModel(name="User",),
    ]
