# Generated by Django 5.0.3 on 2024-04-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post',
            new_name='recipes',
        ),
    ]
