# Generated by Django 4.2.11 on 2024-04-01 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="agent_id",),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[("for rent", "For Rent"), ("for sale", "For Sale")],
                default=2,
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
