# Generated by Django 4.2.11 on 2024-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_property_agent_id_property_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("image", models.ImageField(upload_to="places/")),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Property",),
    ]
