# Generated by Django 4.2.11 on 2024-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_place_delete_property"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="description",),
        migrations.AddField(
            model_name="place",
            name="for_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="for_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="neighborhood",
            field=models.CharField(
                choices=[
                    ("Downtown", "Downtown"),
                    ("Al-Murabba", "Al-Murabba"),
                    ("Al-Olaya", "Al-Olaya"),
                    ("Al-Malaz", "Al-Malaz"),
                    ("Al-Wadi", "Al-Wadi"),
                ],
                default=2,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="price",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Rent", "Rent")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
