# Generated by Django 4.2.11 on 2024-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_place_image_placeimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
