# Generated by Django 4.2.11 on 2024-04-04 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
