# Generated by Django 4.2.11 on 2024-04-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_contact_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="for_rent",),
        migrations.RemoveField(model_name="place", name="for_sale",),
    ]
