# Generated by Django 4.2.11 on 2024-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_place_for_rent_remove_place_for_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place", name="category", field=models.CharField(max_length=50),
        ),
    ]
