# Generated by Django 4.2.11 on 2024-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
