# Generated by Django 4.2.11 on 2024-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_place_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="availability",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Sold", "Sold"),
                ],
                default="Available",
                max_length=10,
            ),
        ),
    ]
