# Generated by Django 4.2.11 on 2024-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_place_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
