# Generated by Django 4.2.11 on 2024-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_place_offer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="for_sale",
            field=models.BooleanField(default=False),
        ),
    ]
