# Generated by Django 4.2.11 on 2024-04-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_place_for_sale"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="availability",),
        migrations.RemoveField(model_name="place", name="for_sale",),
    ]
