# Generated by Django 5.0.2 on 2024-04-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Under review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Under review', max_length=64),
        ),
    ]
