# Generated by Django 5.0.2 on 2024-04-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order_files/'),
        ),
    ]
