# Generated by Django 5.0.2 on 2024-04-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_order_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
