# Generated by Django 5.0.2 on 2024-04-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
