# Generated by Django 5.0.2 on 2024-04-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, upload_to='media/files/'),
        ),
    ]
