# Generated by Django 5.0.2 on 2024-04-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_remove_order_image_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
