# Generated by Django 5.0.2 on 2024-04-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rate',
        ),
    ]
