# Generated by Django 5.0.3 on 2024-04-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linked_link',
            new_name='youtube_link',
        ),
    ]
