# Generated by Django 5.0.3 on 2024-03-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_link',
            new_name='projects_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linked_link',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
