# Generated by Django 5.0.3 on 2024-04-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_instagram_link_profile_projects_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects_link',
        ),
    ]
