# Generated by Django 4.2.11 on 2024-04-14 15:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_booking_email_remove_booking_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="full_name",
            field=models.CharField(default="full name", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(default="0500000000", max_length=15),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 15, 15, 35, 13, 255215, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
