# Generated by Django 4.2.11 on 2024-04-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_address_booking_email_booking_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="status",),
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 15, 16, 7, 11, 435132, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="booking", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="booking",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
