# Generated by Django 4.2.11 on 2024-04-14 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_remove_booking_status_alter_booking_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 15, 22, 58, 5, 47871, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
