# Generated by Django 4.2.11 on 2024-04-14 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_booking_check_out_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 15, 23, 0, 44, 15995, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
