# Generated by Django 5.0.2 on 2024-04-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_orgnization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('unit', 'Unit'), ('final', 'Final'), ('personal', 'Personal')], max_length=100)),
                ('screenshot', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('link', models.URLField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
