# Generated by Django 5.0.2 on 2024-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=2048)),
                ('numberhours', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('expirydate', models.DateTimeField()),
                ('poster', models.ImageField(default='images/default.jpeg', upload_to='images/')),
                ('categories', models.CharField(choices=[('education', 'Education'), ('icts', 'ICTs'), ('languages', 'Languages'), ('law', 'Law')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namedoctor', models.CharField(max_length=2048)),
                ('salary', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('age', models.BooleanField()),
                ('student_id', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
