# Generated by Django 5.0.2 on 2024-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_student_id_doctor_user_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
