# Generated by Django 5.0.3 on 2024-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='images/istockphoto-1300845620-612x612.jpg', upload_to='images/'),
        ),
    ]
