# Generated by Django 5.0.3 on 2024-04-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profileuser_avatar'),
        ('main', '0007_alter_comment_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='recipes',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
            preserve_default=False,
        ),
    ]
