# Generated by Django 5.0.3 on 2024-04-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileuser_recipes'),
        ('main', '0007_alter_comment_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
        ),
    ]
