# Generated by Django 5.0.3 on 2024-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Computer Science', 'Computer Science'), ('Data Science', 'Data Science'), ('Network and Computer Engineering', 'Network And Computer Engineering'), ('Cyber Security', 'Cyber Security')], default='Computer Science', max_length=64),
            preserve_default=False,
        ),
    ]
