# Generated by Django 5.0.1 on 2024-03-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('Fun', 'Fun'), ('Fair', 'Fair')], max_length=20),
        ),
    ]
