# Generated by Django 5.0.1 on 2024-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_story_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('Fun', 'Fun'), ('Fair', 'Fair'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Sci-Fi', 'Science Fiction'), ('Horror', 'Horror')], max_length=20),
        ),
    ]
