# Generated by Django 5.0.1 on 2024-04-02 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
