# Generated by Django 5.0.1 on 2024-04-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_story_saved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('Fun', 'Fun'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Sci-Fi', 'Science-Fiction'), ('Horror', 'Horror')], max_length=20),
        ),
    ]
