# Generated by Django 5.0.1 on 2024-04-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_story_user_alter_story_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
    ]
