# Generated by Django 5.0.3 on 2024-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=2000)),
                ('about_club', models.TextField()),
                ('club_email', models.EmailField(max_length=254)),
                ('club_header', models.ImageField(default='images/default.jpeg', upload_to='images/')),
                ('x_link', models.URLField(blank=True)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
