# Generated by Django 5.0.3 on 2024-04-01 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_description', models.TextField()),
                ('objective', models.TextField()),
                ('event_img', models.ImageField(default='images/event-default.png', upload_to='images/')),
                ('on_site', models.BooleanField()),
                ('theme', models.CharField(choices=[('DataScience', 'Datascience'), ('NetWork', 'Network'), ('CyberSecurity', 'Cybersecurity'), ('SoftwareEngineering', 'Softwareengineering'), ('ArtificialIntelligence', 'Artificialintelligence')], max_length=64)),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop'), ('Program', 'Program'), ('Meeting', 'Meeting'), ('Challenges', 'Challenges')], max_length=64)),
                ('event_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
