# Generated by Django 5.0.3 on 2024-04-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='university_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ContactClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=30)),
                ('message_content', models.TextField()),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
            ],
        ),
    ]
