# Generated by Django 5.0.4 on 2024-04-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Program', 'Program'), ('Meeting', 'Meeting'), ('Challenges', 'Challenges'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('Database', 'Database'), ('Programming', 'Programming'), ('Cyber Security', 'Cyber Security'), ('Software Engineering', 'Software Engineering'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Other', 'Other'), ('General', 'General')], max_length=64),
        ),
    ]
