# Generated by Django 5.0.3 on 2024-04-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_club_university_name_contactclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_description', models.TextField()),
                ('objective', models.TextField()),
                ('event_img', models.ImageField(default='images/event-default.png', upload_to='images/')),
                ('on_site', models.BooleanField()),
                ('theme', models.CharField(choices=[('DataScience', 'Datascience'), ('NetWork', 'Network'), ('CyberSecurity', 'Cybersecurity'), ('SoftwareEngineering', 'Softwareengineering'), ('ArtificialIntelligence', 'Artificialintelligence')], max_length=64)),
                ('event_date_time', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
            ],
        ),
    ]
