# Generated by Django 5.0.4 on 2024-04-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
