# Generated by Django 5.0.2 on 2024-04-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_order_orderdetail_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=6),
        ),
    ]
