# Generated by Django 5.0.2 on 2024-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_orderdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
