# Generated by Django 5.0.3 on 2024-03-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import account.models


class Migration(migrations.Migration):

   initial = True

   dependencies = [
       migrations.swappable_dependency(settings.AUTH_USER_MODEL),
   ]

   operations = [
       migrations.CreateModel(
           name='Profile',
           fields=[
               ('id', models.BigAutoField(auto_created=True,
                primary_key=True, serialize=False, verbose_name='ID')),
               ('about', models.TextField()),
               ('avatar', models.ImageField(default='images/profiles/user-defualt.svg',
                                            upload_to=account.models.group_based_upload_to)),
               ('nationality', models.CharField(choices=[('Saudi Arabia', 'Sa'), (
                  'United Arab Emirates', 'Uae')], default='Saudi Arabia', max_length=20)),
               ('user', models.OneToOneField(
                  on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
           ],
       ),
   ]
