# Generated by Django 5.0.3 on 2024-04-07 14:07

import main.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[main.validator.validate_phone]),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
