# Generated by Django 5.0.3 on 2024-03-27 14:44
from django.db import migrations
from django.conf import settings


def make_profiles(apps, schema_editor):
   User = apps.get_model(settings.AUTH_USER_MODEL)
   Profile = apps.get_model('account', 'Profile')
   profiles = [Profile(user=user)
               for user in User.objects.filter(profile=None)]
   Profile.objects.bulk_create(profiles)


class Migration(migrations.Migration):

   dependencies = [
       ('account', '0001_initial'),
   ]

   operations = [
       migrations.RunPython(make_profiles),

    ]
