# Generated by Django 5.0.3 on 2024-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('اجهزة الكمبيوتر', 'Pc'), ('اجهزة الكمبيوتر المحمول', 'Laptop'), ('قطع الكمبيوتر', 'Parts'), ('اكسسوارات', 'Accessories'), ('برامج', 'Software')], default='اجهزة الكمبيوتر', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
